---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint tasks/*.yml
platforms:
  - name: centos7
    image: centos:7
  - name: centos8
    image: quay.io/centos/centos:stream8
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
