---
- name: Prepare
  hosts: all
  gather_facts: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install cron
      yum:
        name: cronie
        state: present
      when: ansible_os_family == 'RedHat'
      become: true

    - name: Install packages
      package:
        name:
          - zip
          - unzip
        state: present
      become: yes
